[tool.poetry]
authors = ["abersheeran <me@abersheeran.com>"]
description = ""
license = "Apache-2.0"
name = "mingshe"
readme = "README.md"
version = "0.1.0"

homepage = "https://github.com/abersheeran/mingshe"
repository = "https://github.com/abersheeran/mingshe"

classifiers = [
  "Programming Language :: Python :: 3",
]

packages = [
  {include = "mingshe"},
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
isort = "*"

flake8 = "*"

pytest = "^5.4.3"

[tool.poetry.scripts]
mingshe = 'mingshe.commands:main'

[tool.autopep8]
in-place = true
recursive = true
aggressive = 3
max_line_length = 120

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
